app/routes.py
import os
from flask import Blueprint, render_template, g, redirect, send_from_directory, url_for, request, flash, current_app, session
from app.models import Lva, User, Exercise, Grade, Assignment, Registration
from app import db
from werkzeug.utils import secure_filename
from flask_oidc import OpenIDConnect
from app import app

routes = Blueprint('routes', __name__)
oidc = OpenIDConnect(app)

@routes.route('/')
def index():
    if oidc.user_loggedin:  # Wenn der Nutzer eingeloggt ist
        user_info = oidc.user_getinfo(all)  # Rolleninformationen abrufen
        print("UserInfo:", user_info)
        roles = user_info.get('roles', [])
        #user_email = oidc.user_getfield("email")  # Holen der Mail aus dem Token

        # Überprüfen der Rolle
        if "professor" in roles:
            user_type = "professor"
        elif "student" in roles:
            user_type = "student"
        else:
            print("User ist weder Student noch Professor!")
            user_type = "student" # wird als Student behandelt

        user = User.query.filter_by(email=oidc.user_getfield("email")).first()   # <- Nimmt die Email- Adresse aus dem Keycloak Token und sucht nach dieser in der DB
        #user = User.query.filter_by(email="student1@example.com").first()
        #user = User.query.filter_by(email="instructor2@example.com").first()
        lvas = Lva.query.all()

# Problem: es wird nur eine LVA pro LVA-Leiter angezeigt
        #lva_von_leiter = Lva.query.filter_by(instructor_id=user.id).first()     #all falls lva leiter mehrere lvas hat
        lvaLeiter_lvas = Lva.query.filter_by(instructor_id=user.id).all()

       # if lva_von_leiter is not None:
        #    registrations = Registration.query.filter_by(lva_id=lva_von_leiter.lva_number).all()
       # else:
        #    registrations = []

        if user_type!='professor':
            return render_template('student.html', lvas = lvas, user = user)
        else:
            return render_template('lva-leiter.html', lvaLeiter_lvas = lvaLeiter_lvas, user = user)
    else:   # Falls der User nicht eingeloggt ist:
            return render_template('login.html')
        #return '''
        #            <h1>Welcome to LVA-Manager 3000!</h1>
        #            <p>You are not logged in.</p>
        #           <a href="/login"><button>Log in</button></a>
        #        '''
    
@routes.route('/logout', methods=['POST'])
def logout():
    print("User Logout")
    # Keycloak-Logout-URL mit Token und redirect_uri
    #id_token = oidc.get_access_token()
    oidc.logout()      # Lokale Flask-Session beenden
    session.clear()  # Zusätzliche Sicherheit, um die Sitzung zu bereinigen

    keycloak_logout_url = (
        "http://localhost:8080/realms/lvaManager/protocol/openid-connect/logout"
    )

    # Weiterleitung zur Keycloak-Logout-Seite
    return redirect(keycloak_logout_url)

@routes.route('/Lva/<int:lva_number>')
def lva(lva_number):
    user = User.query.filter_by(email=oidc.user_getfield("email")).first()
    lva = Lva.query.get_or_404(lva_number)
    is_registered = Registration.query.filter_by(student_id = user.id, lva_id = lva_number).first() is not None
    exercises = Exercise.query.filter_by(lva_id=lva_number).all()
    return render_template('lva.html', lva = lva, is_registered = is_registered, user = user, exercises = exercises)
    

@routes.route('/Lva/<int:lva_number>/register', methods=['POST'])
def register_lva(lva_number):
    user = User.query.filter_by(email=oidc.user_getfield("email")).first()

    # Anmeldung zum Kurs
    registration = Registration(student_id=user.id, lva_id=lva_number)
    db.session.add(registration)
    db.session.commit()
    return redirect(url_for('routes.lva', lva_number=lva_number))

@routes.route('/Lva/<int:lva_number>/deregister', methods=['POST'])
def deregister_lva(lva_number):
    user = User.query.filter_by(email=oidc.user_getfield("email")).first()
    registration = Registration.query.filter_by(student_id = user.id, lva_id = lva_number).first()
    if registration:
        db.session.delete(registration)
        db.session.commit()
    return redirect(url_for('routes.lva', lva_number=lva_number))


@routes.route('/exercise/<int:exercise_id>')
def exercise(exercise_id):
    user = User.query.filter_by(email=oidc.user_getfield("email")).first()
    exercise = Exercise.query.get_or_404(exercise_id)
    assignment = Assignment.query.filter_by(student_id=user.id, exercise_id=exercise_id).first()
    return render_template('exercise.html', user = user, exercise=exercise, assignment=assignment)



UPLOAD_FOLDER = 'uploads'
ALLOWED_EXTENSIONS = {'pdf'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@routes.route('/student/<int:student_id>/assignments/<int:lva_id>')
def assignments(student_id, lva_id):
    user = User.query.filter_by(email=oidc.user_getfield("email")).first()
    student = User.query.filter_by(id=student_id).first()
    lva = Lva.query.filter_by(lva_number=lva_id).first()

    return render_template('assignments.html', student=student, user = user, lva = lva)


@routes.route('/student/<int:student_id>/assignments_detail/<int:assignment_id>')
def assignment_detail(student_id, assignment_id):
    user = User.query.filter_by(email=oidc.user_getfield("email")).first()
    assignment = Assignment.query.filter_by(id=assignment_id).first()
    student = User.query.filter_by(id=student_id).first()
    return render_template('assignment_detail.html', assignment = assignment, student=student, user = user)


@routes.route('/assignments/<int:assignment_id>/download')
def download_assignment(assignment_id):
    assignment = Assignment.query.get_or_404(assignment_id)
    student_id = assignment.student_id
    upload_folder = current_app.config['UPLOAD_FOLDER']
    file_path = assignment.file_path
        
    # Überprüfen, ob die Datei wirklich existiert
    if not os.path.exists(os.path.join(upload_folder, file_path)):
        print(f"Redirecting to assignment_detail with student_id: {student_id} and assignment_id: {assignment_id}")
        flash("File not found.")
        return redirect(url_for('routes.assignment_detail', student_id=student_id, assignment_id=assignment_id))
    
    # Sende die Datei aus dem Upload-Verzeichnis
    return send_from_directory(directory=upload_folder, path=file_path, as_attachment=True)


@routes.route('/assignments/<int:assignment_id>/grade', methods=['POST'])
def grade_assignment(assignment_id):
    assignment = Assignment.query.get_or_404(assignment_id)
    
    # Note aus dem Formular
    grade_value = request.form.get('grade')
    
    # vorhande Bewertung holen
    existing_grade = Grade.query.filter_by(assignment_id=assignment.id).first()
    #wenn es schon eine Bewertung gibt, wird es überschrieben
    if existing_grade:
        existing_grade.grade = grade_value
    #wenn keine gibt wird eine neue Bewertung erstellt
    else:
        # Neue Bewertung erstellen
        grade = Grade(assignment_id=assignment.id, grade=grade_value)
        db.session.add(grade)
    
    db.session.commit()
    
    return redirect(url_for('routes.assignment_detail', student_id=assignment.student_id, assignment_id=assignment.id))


@routes.route('/exercise/<int:exercise_id>/submit', methods=['POST'])
def submit_assignment(exercise_id):
    user = User.query.filter_by(email=oidc.user_getfield("email")).first()

    if 'file' not in request.files:
        flash('No file part')
        return redirect(request.url)

    file = request.files['file']
    
    if file.filename == '':
        flash('No selected file')
        return redirect(request.url)

    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)

        # überprüfen ob der user bereits eine abgabe für diese übung hat
        assignment = Assignment.query.filter_by(student_id=user.id, exercise_id=exercise_id).first()
        #wenn ja wird die abgabe überschrieben
        if assignment:
            if os.path.exists(os.path.join(current_app.config['UPLOAD_FOLDER'], assignment.file_path)):
                os.remove(os.path.join(current_app.config['UPLOAD_FOLDER'], assignment.file_path))
            assignment.file_path = filename
        #wenn nicht wird eine neue Abgabe erstellt
        else:
            assignment = Assignment(student_id=user.id, exercise_id=exercise_id, file_path=filename)  # Only save the filename
            db.session.add(assignment)

        file.save(file_path)
        
        db.session.commit()

        flash('File uploaded successfully!')
        return redirect(url_for('routes.exercise', exercise_id=exercise_id))

    else:
        flash('Invalid file type. Only PDF files are allowed.')
        return redirect(request.url)

app/templates/assignment_detail.html
{% extends "base.html" %}
{% block content %}
    <h5>Assignment: {{ assignment.exercise.title }}</h5>
    <h6>Von: {{ student.firstname }} {{ student.lastname }}</h6>
    
    <!-- Download Link -->
    <a href="{{ url_for('routes.download_assignment', assignment_id=assignment.id) }}" class="btn btn-secondary">
        Datei herunterladen
    </a>
    <br>
    <br>
    <!-- Formular zur Bewertung -->
    <form action="{{ url_for('routes.grade_assignment', assignment_id=assignment.id) }}" method="POST">
        <div class="form-group">
            <label for="grade">Bewertung (0-100):</label>
            <input type="number" name="grade" id="grade" class="form-control" min="0" max="100" required>
        </div>
        {% if assignment.grade: %}
            <h6>Bewertung: {{ assignment.grade.grade }} Punkte</h6>
            <br>
            <button type="submit" class="btn btn-primary">Bewertung überschreiben</button>
        {% else: %}
            <h6>Bewertung: nicht bewertet</h6>
            <br>
            <button type="submit" class="btn btn-primary">Bewertung abgeben</button>
        {% endif %}
        
    </form>
    <br>
    
    
{% endblock %}

app/templates/assignments.html
{% extends "base.html" %}
{% block content %}
    <h3>Assignments von: {{ student.firstname }} {{ student.lastname }}</h3>
    <ul class="list-group">
    {% for exercise in lva.exercises %}
        {% for assignment in exercise.assignments %}
            {% if assignment.student_id == student.id %}
                <li class="list-group-item"><a href="{{ url_for('routes.assignment_detail', student_id = student.id, assignment_id = assignment.id) }}">Assignment für {{ assignment.exercise.title }} </a></li>
            {% endif %}
        {% endfor %}
    {% endfor %}
    </ul>
    
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/89cef35a0d.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>




    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar"> 
            <div class="navbar-nav">
                
            </div>
        </div>
    </nav> -->
    <div class="container">
        <form action="/" class="home-form">
            <button class="elegant-button" type="submit">Home</button>
        </form>

        <h5 align = right class="loggedIn-user">logged in as {{user.email}} ({{user.firstname}} {{user.lastname}})</h5>

        <form action="/logout" method="post" class="logout-form">
            <button class="elegant-button" type="submit">Logout</button>
        </form>
        {% block content %}
        {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

app/templates/exercise.html
{% extends "base.html" %}
{% block content %}
    <h1>{{ exercise.title }}</h1>
    <h3>{{ exercise.description }}</h3>
    <h3>Abgabe:</h3>
   

    <form action="{{ url_for('routes.submit_assignment', exercise_id=exercise.id) }}" method="POST" enctype="multipart/form-data">
        <div class="form-group">
            <label for="file">PDF-Datei hochladen:</label>
            <input type="file" name="file" id="file" accept="application/pdf" class="form-control">
        </div> 
        {% if assignment %}
            <p style="color: lightgreen;">Bereits abgegeben: {{ assignment.file_path }}</p>
        {% endif %}
        <br>
        <button type="submit" class="btn btn-primary">
            {% if assignment %}Überschreiben{% else %}Abgeben{% endif %}
        </button>
    </form>
    <br>
    {% if assignment.grade: %}
        <h6>Bewertung: {{ assignment.grade.grade }} Punkte</h6>
    {% else: %}
        <h6>Bewertung: nicht bewertet</h6>
    {% endif %}
{% endblock %}

app/templates/home.html
<!-- {% extends "base.html" %} 

{% block title %}Home{% endblock %}

{% block content %}    
<h1>this is the Homepage</h1> 
<h2>asdf</h2>  
{% endblock %} -->

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/89cef35a0d.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <title>{% block title %}Home{% endblock %}</title>
</head>




{% block content %}
<div class="container">
    <h1 class="display-4 text-primary">LVA-Manager</h1>
    <p>You are not logged in!</p>
    <a href="/login"><button>Log in</button></a>
</div>
{% endblock %}

app/templates/lva-leiter.html
{% extends "base.html" %}
{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Registrierte Studenten</h1>
        <div class="column">
            {% for lva in lvaLeiter_lvas %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h2 class="h5 mb-0">{{ lva.title }}</h2>
                        </div>
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                {% for registration in lva.registrations %}
                                    <li class="list-group-item">
                                        <a href="{{ url_for('routes.assignments', student_id=registration.student.id, lva_id=lva.lva_number) }}" class="text-decoration-none">
                                            {{ registration.student.firstname }} {{ registration.student.lastname }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/lva.html
{% extends "base.html" %}
{% block content %}
    <div class="container mt-5">
        <h1 class="display-4 text-primary">{{ lva.title }}</h1>
        <p class="lead text-secondary mb-4">{{ lva.description }}</p>

        <div class="mb-4">
            <h5 class="text-muted">Lva-Leiter:</h5>
            <p class="h5">{{ lva.instructor.firstname }} {{ lva.instructor.lastname }}</p>
        </div>

        <!-- Anmeldung -->
        <div class="mb-4">
            <h5 class="text-muted">Anmeldung:</h5>
            {% if not is_registered %}
                <form action="{{ url_for('routes.register_lva', lva_number=lva.lva_number) }}" method="post">
                    <button type="submit" class="btn btn-success">Anmelden</button>
                </form>
            {% else %}
                <p class="h5 text-success">Sie sind bereits angemeldet</p>
                <form action="{{ url_for('routes.deregister_lva', lva_number=lva.lva_number) }}" method="post">
                    <button type="submit" class="btn btn-danger">Abmelden</button>
                </form>
            {% endif %}
        </div>

        <!-- Übungen -->
        {% if is_registered %}
            <h2 class="h4 text-primary mt-4">Übungen</h2>
            <ul class="list-group mt-3">
                {% for exercise in exercises %}
                    <li class="list-group-item">
                        <a href="{{ url_for('routes.exercise', lva_number=lva.lva_number, exercise_id=exercise.id) }}" 
                           class="text-decoration-none text-dark">
                            {{ exercise.title }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

app/templates/student.html
{% extends "base.html" %}
{% block content %}
    <h1>Lehrveranstaltungen:</h1>
    <ul class="list-group">
    {% for lva in lvas: %}
    <li class="list-group-item"><a href="{{ url_for('routes.lva', lva_number = lva.lva_number) }}">{{lva.title}}</a></li>
    {% endfor %}
    </ul>
{% endblock %}